# Generated by Django 3.2.8 on 2021-10-21 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.CharField(choices=[('RHP', 'Right Handed Pitcher'), ('LHP', 'Left Handed Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter')], default='RHP', max_length=3)),
                ('handedness', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], default='Right', max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('profile_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
